Update build-darwin-arm64.yml

diff --git a/.github/workflows/build-darwin-arm64.yml b/.github/workflows/build-darwin-arm64.yml
--- a/.github/workflows/build-darwin-arm64.yml
+++ b/.github/workflows/build-darwin-arm64.yml
@@ -51,25 +51,35 @@ jobs:
           cp ~/go/pkg/mod/github.com/initia-labs/movevm@*/api/libcompiler.dylib initia_${VERSION}/libcompiler.${ARCH_NAME}.dylib
           mv initiad initia_${VERSION}/
           tar -czvf initia_${VERSION}_Darwin_${ARCH_NAME}.tar.gz initia_${VERSION}
-      - name: Google Auth
-        uses: 'google-github-actions/auth@v2'
+      - name: Upload Release Asset
+        if: startsWith(github.ref, 'refs/tags/')
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
         with:
-          credentials_json: '${{ secrets.GCP_SA_KEY }}'
-      - name: Set up Cloud SDK
-        uses: 'google-github-actions/setup-gcloud@v2'
-      - name: Upload to GCS
-        env:
-          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
-        run: |
-          gsutil cp ./build/initia_${VERSION}_Darwin_${ARCH_NAME}.tar.gz gs://${GCS_BUCKET}/initia/
-      - name: Verify upload and Generate public URL
-        env:
-          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
-        run: |
-          if gsutil stat gs://${GCS_BUCKET}/initia/initia_${VERSION}_Darwin_${ARCH_NAME}.tar.gz; then
-            echo "File successfully uploaded"
-            echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/initia/initia_${VERSION}_Darwin_${ARCH_NAME}.tar.gz" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "File upload failed"
-            exit 1
-          fi
+          upload_url: ${{ github.event.release.upload_url }}
+          asset_path: ./build/initia_${{ env.VERSION }}_Darwin_${{ env.ARCH_NAME }}.tar.gz
+          asset_name: initia_${{ env.VERSION }}_Darwin_${{ env.ARCH_NAME }}.tar.gz
+          asset_content_type: application/gzip          
+      # - name: Google Auth
+      #   uses: 'google-github-actions/auth@v2'
+      #   with:
+      #     credentials_json: '${{ secrets.GCP_SA_KEY }}'
+      # - name: Set up Cloud SDK
+      #   uses: 'google-github-actions/setup-gcloud@v2'
+      # - name: Upload to GCS
+      #   env:
+      #     GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
+      #   run: |
+      #     gsutil cp ./build/initia_${VERSION}_Darwin_${ARCH_NAME}.tar.gz gs://${GCS_BUCKET}/initia/
+      # - name: Verify upload and Generate public URL
+      #   env:
+      #     GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
+      #   run: |
+      #     if gsutil stat gs://${GCS_BUCKET}/initia/initia_${VERSION}_Darwin_${ARCH_NAME}.tar.gz; then
+      #       echo "File successfully uploaded"
+      #       echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/initia/initia_${VERSION}_Darwin_${ARCH_NAME}.tar.gz" >> $GITHUB_STEP_SUMMARY
+      #     else
+      #       echo "File upload failed"
+      #       exit 1
+      #     fi
