Update build-darwin-amd64.yml

diff --git a/.github/workflows/build-darwin-amd64.yml b/.github/workflows/build-darwin-amd64.yml
--- a/.github/workflows/build-darwin-amd64.yml
+++ b/.github/workflows/build-darwin-amd64.yml
@@ -34,6 +34,17 @@ jobs:
           apt-get update
           apt-get install -y libdl2 libc6
 
+      - name: Find libdl.so.2 and set LD_LIBRARY_PATH
+        run: |
+          LIBDL_PATH=$(find / -name "libdl.so.2" 2>/dev/null)
+          echo "libdl.so.2 found at: $LIBDL_PATH"
+          if [ -z "$LIBDL_PATH" ]; then
+            echo "libdl.so.2 not found"
+            exit 1
+          fi
+          export LD_LIBRARY_PATH=$(dirname $LIBDL_PATH):$LD_LIBRARY_PATH
+          echo "LD_LIBRARY_PATH set to: $LD_LIBRARY_PATH"
+
       - name: Set up Go
         run: |
           wget https://golang.org/dl/go1.22.4.linux-amd64.tar.gz
@@ -57,7 +68,7 @@ jobs:
 
       - name: Build for Darwin AMD64
         run: |
-          export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
+          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
           CC=gcc
           GOARCH=amd64 GOOS=darwin CGO_ENABLED=1 CC=$CC go build -mod=readonly -tags 'netgo ledger' -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=initia -X github.com/cosmos/cosmos-sdk/version.AppName=initiad -X github.com/cosmos/cosmos-sdk/version.Version=${GITHUB_SHA} -X github.com/cosmos/cosmos-sdk/version.Commit=${GITHUB_SHA} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/cometbft/cometbft/version.TMCoreSemVer=v0.0.0-20240704071957-c46468756c01 -w -s' -trimpath -o build/initiad ./cmd/initiad
           cd ./build
