Update build-darwin-amd64.yml

diff --git a/.github/workflows/build-darwin-amd64.yml b/.github/workflows/build-darwin-amd64.yml
--- a/.github/workflows/build-darwin-amd64.yml
+++ b/.github/workflows/build-darwin-amd64.yml
@@ -1,73 +1,68 @@
-name: Build Linux AMD64
-
+name: Build Darwin AMD64
 on:
   workflow_call:
     inputs:
       arch:
         required: true
         type: string
-
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: macos-12
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
           go-version: '1.22.4'
-
       - name: Set environment variables
         run: |
           echo "GOARCH=${{ inputs.arch }}" >> $GITHUB_ENV
-          echo "GOOS=linux" >> $GITHUB_ENV
-          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
-            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
-          else
-            echo "VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
-          fi
-
+          echo "GOOS=darwin" >> $GITHUB_ENV
+          echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
+      - name: Ensure dependencies
+        run: go mod tidy
       - name: Print environment variables
         run: |
           echo "GOARCH=${GOARCH}"
           echo "GOOS=${GOOS}"
-          echo "VERSION=${VERSION}"
-
-      - name: Build for Linux AMD64
+          echo "GITHUB_SHA=${GITHUB_SHA}"
+      - name: Build for Darwin AMD64
         run: |
           export GOARCH=${GOARCH}
           export GOOS=${GOOS}
-          make build-linux-with-shared-library
+          go build -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=initia -X github.com/cosmos/cosmos-sdk/version.AppName=initiad -X github.com/cosmos/cosmos-sdk/version.Version=${GITHUB_SHA} -X github.com/cosmos/cosmos-sdk/version.Commit=${GITHUB_SHA} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/cometbft/cometbft/version.TMCoreSemVer=v0.0.0-20240704071957-c46468756c01 -w -s' -trimpath -o build/initiad ./cmd/initiad
+          chmod +x build/initiad
+          ls -lh build/initiad
+          file build/initiad
+          ./build/initiad --version || echo "Binary execution failed"
+          ./build/initiad version || echo "Binary execution failed"
+      - name: Package build artifacts
+        run: |
           cd ./build
-          mkdir -p initia_${VERSION}
-          mv libmovevm.so initia_${VERSION}/libmovevm.${GOARCH}.so
-          mv libcompiler.so initia_${VERSION}/libcompiler.${GOARCH}.so
-          mv initiad initia_${VERSION}/
-          tar -czvf initia_${VERSION}_Linux_${GOARCH}.tar.gz initia_${VERSION}
-
+          mkdir -p initia_build
+          cp ~/go/pkg/mod/github.com/initia-labs/movevm@*/api/libmovevm.dylib initia_build/libmovevm.${GOARCH}.dylib
+          cp ~/go/pkg/mod/github.com/initia-labs/movevm@*/api/libcompiler.dylib initia_build/libcompiler.${GOARCH}.dylib
+          mv initiad initia_build/
+          tar -czvf initia_Darwin_${GOARCH}.tar.gz initia_build
       - name: Google Auth
         uses: 'google-github-actions/auth@v2'
         with:
           credentials_json: '${{ secrets.GCP_SA_KEY }}'
-
       - name: Set up Cloud SDK
         uses: 'google-github-actions/setup-gcloud@v2'
-
       - name: Upload to GCS
         env:
           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
         run: |
-          gsutil cp ./build/initia_${VERSION}_Linux_${GOARCH}.tar.gz gs://${GCS_BUCKET}/initia/
-
+          gsutil cp ./build/initia_Darwin_${GOARCH}.tar.gz gs://${GCS_BUCKET}/initia/
       - name: Verify upload and Generate public URL
         env:
           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
         run: |
-          if gsutil stat gs://${GCS_BUCKET}/initia/initia_${VERSION}_Linux_${GOARCH}.tar.gz; then
+          if gsutil stat gs://${GCS_BUCKET}/initia/initia_Darwin_${GOARCH}.tar.gz; then
             echo "File successfully uploaded"
-            echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/initia/initia_${VERSION}_Darwin_${GOARCH}.tar.gz" >> $GITHUB_STEP_SUMMARY
+            echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/initia/initia_Darwin_${GOARCH}.tar.gz" >> $GITHUB_STEP_SUMMARY
           else
             echo "File upload failed"
             exit 1
