Update build-linux-arm64.yml

diff --git a/.github/workflows/build-linux-arm64.yml b/.github/workflows/build-linux-arm64.yml
--- a/.github/workflows/build-linux-arm64.yml
+++ b/.github/workflows/build-linux-arm64.yml
@@ -35,18 +35,21 @@ jobs:
         run: |
           docker run --rm --platform linux/arm64 -v $(pwd):/go/src/app -w /go/src/app -e GOARCH -e GOOS -e VERSION arm64v8/golang:1.22.4 \
             sh -c "
+              git config --global --add safe.directory /go/src/app
               export GOARCH=${GOARCH}
               export GOOS=${GOOS}
+              go mod download
+              apt-get update && apt-get install -y make docker.io
               make build-linux-with-shared-library
               cd ./build
               mkdir -p initia_${VERSION}
-              mv libmovevm.so initia_${VERSION}/libmovevm.${GOARCH}.so
-              mv libcompiler.so initia_${VERSION}/libcompiler.${GOARCH}.so
-              mv initiad initia_${VERSION}/
+              if [ -f libmovevm.so ]; then mv libmovevm.so initia_${VERSION}/libmovevm.${GOARCH}.so; fi
+              if [ -f libcompiler.so ]; then mv libcompiler.so initia_${VERSION}/libcompiler.${GOARCH}.so; fi
+              if [ -f initiad ]; then mv initiad initia_${VERSION}/; fi
               tar -czvf initia_${VERSION}_Linux_${GOARCH}.tar.gz initia_${VERSION}
               mv initia_${VERSION}_Linux_${GOARCH}.tar.gz /go/src/app/
             "
-      
+
       - name: List files
         run: ls -l
       
@@ -62,7 +65,12 @@ jobs:
         env:
           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
         run: |
-          gsutil cp ./initia_${VERSION}_Linux_${GOARCH}.tar.gz gs://${GCS_BUCKET}/initia/
+          if [ -f ./initia_${VERSION}_Linux_${GOARCH}.tar.gz ]; then
+            gsutil cp ./initia_${VERSION}_Linux_${GOARCH}.tar.gz gs://${GCS_BUCKET}/initia/
+          else
+            echo "Build artifact not found"
+            exit 1
+          fi
       
       - name: Verify upload and Generate public URL
         env:
