Update build-linux-arm64.yml

diff --git a/.github/workflows/build-linux-arm64.yml b/.github/workflows/build-linux-arm64.yml
--- a/.github/workflows/build-linux-arm64.yml
+++ b/.github/workflows/build-linux-arm64.yml
@@ -1,28 +1,76 @@
+# name: Build ARM64
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
+      
+#       - name: Set up QEMU
+#         uses: docker/setup-qemu-action@v2
+      
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v2
+      
+#       - name: Build Docker image and extract binary
+#         run: |
+#           docker buildx build --platform linux/arm64 -t myapp:arm64 -f .github/workflows/Dockerfile.arm --load .
+#           docker create --name temp myapp:arm64
+#           docker cp temp:/root/initiated ./initiated-arm64
+#           docker rm temp
+      
+#       - name: Google Auth
+#         uses: 'google-github-actions/auth@v2'
+#         with:
+#           credentials_json: '${{ secrets.GCP_SA_KEY }}'
+      
+#       - name: Set up Cloud SDK
+#         uses: 'google-github-actions/setup-gcloud@v2'
+      
+#       - name: Upload to GCS
+#         env:
+#           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
+#         run: |
+#           gsutil cp initiated-arm64 gs://${GCS_BUCKET}/
+      
+#       - name: Verify upload and Generate public URL
+#         env:
+#           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
+#         run: |
+#           if gsutil stat gs://${GCS_BUCKET}/initiated-arm64; then
+#             echo "File successfully uploaded"
+#             echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/initiated-arm64" >> $GITHUB_STEP_SUMMARY
+#           else
+#             echo "File upload failed"
+#             exit 1
+#           fi
+
 name: Build ARM64
 on:
   push:
     branches:
       - main
   pull_request:
+
 jobs:
   build:
     runs-on: ubuntu-latest
+    container:
+      image: arm64v8/golang:1.22.4
+      options: --platform linux/arm64
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-      
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      
-      - name: Build Docker image and extract binary
+      - name: Build
         run: |
-          docker buildx build --platform linux/arm64 -t myapp:arm64 -f .github/workflows/Dockerfile.arm --load .
-          docker create --name temp myapp:arm64
-          docker cp temp:/root/initiated ./initiated-arm64
-          docker rm temp
+          go mod download
+          CGO_ENABLED=1 go build -o initiated ./cmd/initiad
       
       - name: Google Auth
         uses: 'google-github-actions/auth@v2'
@@ -36,15 +84,15 @@ jobs:
         env:
           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
         run: |
-          gsutil cp initiated-arm64 gs://${GCS_BUCKET}/
+          gsutil cp initiated gs://${GCS_BUCKET}/
       
       - name: Verify upload and Generate public URL
         env:
           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
         run: |
-          if gsutil stat gs://${GCS_BUCKET}/initiated-arm64; then
+          if gsutil stat gs://${GCS_BUCKET}/initiated; then
             echo "File successfully uploaded"
-            echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/initiated-arm64" >> $GITHUB_STEP_SUMMARY
+            echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/initiated" >> $GITHUB_STEP_SUMMARY
           else
             echo "File upload failed"
             exit 1
